version: '3.8'

services:
  db:
    image: postgres:16
    container_name: city_lion_db
    environment:
      - POSTGRES_DB=city_lion
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - city_lion_network

networks:
  city_lion_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
